packages:
  - ./apps/*
  - ./packages/*

catalog:
  typescript: 5.8.3
  eslint: 9.34.0
  prettier: 3.6.2

  zod: 4.0.5
  lint-staged: 16.1.2
  react: 19.0.3
  react-dom: 19.0.3

  "@types/react": 19.0.14
  "@types/node": 22.10.10
  "@types/formidable": 2.0.5
